---

# Available IPs:
#
# IPv4 Block:	172.16.48.0/20
#
# Used by OpenStack:
#
# br-infra:	172.16.48.0/24
# br-mgmt:	172.16.49.0/24
# br-vxlan:	172.16.50.0/24
# br-storage:	172.16.51.0/24
# ...
# Floating IPs:	172.16.62.0/23

cidr_networks:

  container: 172.16.49.0/24
  tunnel: 172.16.50.0/24
  storage: 172.16.51.0/24

used_ips:
  - "172.16.49.250,172.16.49.254"
  - "172.16.49.1,172.16.49.64"
  - "172.16.50.1,172.16.50.64"
  - "172.16.51.1,172.16.51.64"

#container_tech: nspawn

global_overrides:

#  external_lb_vip_address: os-1.ca-east-1.tcmc.cloud
#  internal_lb_vip_address: os-internal-1.ca-east-1.tcmc.cloud

  external_lb_vip_address: 172.16.48.250
  internal_lb_vip_address: 172.16.49.250

  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"

  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
        is_ssh_address: true
#    - network:
#        container_bridge: "br-vxlan"
#        container_type: "veth"
#        container_interface: "eth10"
#        ip_from_q: "tunnel"
#        type: "vxlan"
#        range: "10001:99999"
#        net_name: "vxlan"
#        group_binds:
#          - neutron_linuxbridge_agent
#    - network:
#        container_bridge: "br-vlan"
#        container_type: "veth"
#        container_interface: "eth12"
#        host_bind_override: "ens2"
#        type: "flat"
#        net_name: "flat"
#        group_binds:
#          - neutron_linuxbridge_agent
#    - network:
#        container_bridge: "br-vlan"
#        container_type: "veth"
#        container_interface: "eth11"
#        type: "vlan"
#        range: "100:4090"
#        net_name: "vlan"
#        group_binds:
#          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
          - ceph-osd

###
### Infrastructure
###

# ceph-mon containers
ceph-mon_hosts:
  vceinfr-1:
    ip: 172.16.49.21
  vceinfr-2:
    ip: 172.16.49.22
  vceinfr-3:
    ip: 172.16.49.23

# ceph-rgw containers
ceph-rgw_hosts:
  vcerdgw-1:
    ip: 172.16.49.24
  vcerdgw-2:
    ip: 172.16.49.25
  vcerdgw-3:
    ip: 172.16.49.26

# ceph-meta containers
ceph-meta_hosts:
  vcemeta-1:
    ip: 172.16.49.27
  vcemeta-2:
    ip: 172.16.49.28
  vcemeta-3:
    ip: 172.16.49.29

# ceph-osd
ceph-osd_hosts:
  c1str1:
    ip: 172.16.49.30

# galera, memcache, rabbitmq, utility
shared-infra_hosts:
  vosctrl-1:
    ip: 172.16.49.1
  vosctrl-2:
    ip: 172.16.49.2
  vosctrl-3:
    ip: 172.16.49.3

# repository (apt cache, python packages, etc)
repo-infra_hosts:
  vosctrl-1:
    ip: 172.16.49.1
  vosctrl-2:
    ip: 172.16.49.2
  vosctrl-3:
    ip: 172.16.49.3

# rsyslog server
log_hosts:
  voslog-1:
    ip: 172.16.49.10

###
### OpenStack
###

# keystone
identity_hosts:
  vosctrl-1:
    ip: 172.16.49.1
  vosctrl-2:
    ip: 172.16.49.2
  vosctrl-3:
    ip: 172.16.49.3

# glance
# The settings here are repeated for each infra host.
# They could instead be applied as global settings in
# user_variables, but are left here to illustrate that
# each container could have different storage targets.
image_hosts:
  vosctrl-1:
    ip: 172.16.49.1
  vosctrl-2:
    ip: 172.16.49.2
  vosctrl-3:
    ip: 172.16.49.3

# horizon
dashboard_hosts:
  vosctrl-1:
    ip: 172.16.49.1
  vosctrl-2:
    ip: 172.16.49.2
  vosctrl-3:
    ip: 172.16.49.3

# gnocchi (telemetry metrics storage)
metrics_hosts:
  vosctrl-1:
    ip: 172.16.49.1
  vosctrl-2:
    ip: 172.16.49.2
  vosctrl-3:
    ip: 172.16.49.3
